### ISSUE TITLE
why I can not use camera  control button to wake up custom slider 

### ISSUE THREAD

**Issue by Fihade** [ToshihiroGoto/CameraControl#1]
click control button only to jump to system camera

**Comment by ToshihiroGoto** [comment]
That functionality has not been implemented.
The following repositories may be helpful.
https://github.com/JuniperPhoton/LockedCameraCaptureExtensionDemo

**Comment by Fihade** [comment]
Thank u, I implemented this camera control function to anywhere, https://github.com/Fihade/CameraControl
